config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :conversations
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'pages#landing'
  post '/', to: 'pages#landing'

  post 'update_university', to: 'pages#update_university'

  get 'students/show', to: 'students#show'
  post 'students/show', to: 'students#show'

  get 'students/details', to: 'students#details'

  get 'ratings/index', to: 'ratings#index'

  post 'ratings/create', to: 'ratings#create'
  get 'ratings/new', to: 'ratings#new'

  resources :conversations do
    resources :messages
  end

  get 'students/index', to: 'students#index'
  resources :students

  get 'scores/index', to: 'scores#index'
  resources :scores

  get 'educations/index', to: 'educations#index'
  resources :educations

  get 'student_applications/index'
  resources :student_applications
  post 'student_applications/save_application'

  get 'programs/index'
  resources :programs

  get 'admin', to: 'pages#admin'
  post 'pages/update_users', to: 'pages#update_users'

  patch 'students/:id', to: 'students#update'                          # update (as needed)
  put 'students/:id', to: 'students#update'

  get 'faculty/index', to: 'student_applications#faculty_index'

  post 'ratings/create_from_application', to: 'ratings#create_from_application'
  post 'application/update_status', to: 'student_applications#update_status'

  get 'ratings/application', to: 'ratings#show_application_ratings'
  get 'ratings/user', to: 'ratings#show_user_ratings'

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :educations, dependent: :destroy
  has_one :score, dependent: :destroy
  has_many :student_applications, dependent: :destroy
  accepts_nested_attributes_for :educations, :score, :student_applications, allow_destroy: true
  belongs_to :user, :foreign_key=> :email_id, :primary_key => :email
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :check_student, except: [:index]

  def check_student
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.student?)
  end

  def index

    order = params[:order]
    ordering = 'first_name desc'
    @students = Student.all

    if order == 'age'
      ordering = 'age ASC'
      @students = Student.all.reorder(ordering)
    elsif order == 'first_name'
      ordering = 'first_name desc'
      @students = Student.all.reorder(ordering)
    elsif order == 'gpa'
      ordering = 'educations.gpa desc'
      @students = Student.all.includes(:educations).reorder(ordering)
    elsif order == 'sat'
      ordering = 'scores.sat desc'
      @students = Student.all.includes(:scores).reorder(ordering)
    elsif order == 'act'
      ordering = 'scores.act desc'
      @students = Student.all.includes(:scores).reorder(ordering)
    end

    #@students = Student.all.reorder(ordering)

  end

  def show
    @student = Student.find_by_email_id(current_user.email) #this will have to come from the session after login
    if params[:search_box] == nil || params[:search_box] == ''
      @universities = [ Hash['school.name' => 'Enter a valid university name to search.', '2015.admissions.admission_rate.overall' => ' ', '2015.admissions.test_requirements' => ''] ]
    else
      response = StudentsController.search_collegeapi(params[:search_box])
      json = JSON.parse(response)
      @universities = json['results']
    end

    students = Student.all.includes(:educations).order('educations.gpa desc')
    i = 1.0
    students.each do |s|
      if s.id == @student.id
        break
      end
      i = i+1
    end
    @gpa_rank = i
    @total = students.length

    students = Student.all.includes(:score).reorder('scores.act desc')
    i = 1.0
    students.each do |s|
      if s.id == @student.id
        break
      end
      i = i+1
    end

    @act_rank = i

  end

  def self.search_collegeapi(terms)
    string = 'https://api.data.gov/ed/collegescorecard/v1/schools.json?school.name='+ terms + '&fields=id,school.school_url,school.city,school.state,2015.admissions.test_requirements,2015.admissions.admission_rate.overall,2015.cost.avg_net_price.public,school.name,2013.student.size&api_key=HAm234DRylBdwr9s80X76mTZTDubUE7Zi1lrUSn0'
    #URI.open("https://api.data.gov/ed/collegescorecard/v1/schools.json?school.name=#{terms}&fields=id,school.school_url,school.city,school.state,2015.admissions.test_requirements,2015.admissions.admission_rate.overall,2015.cost.avg_net_price.public,school.name,2013.student.size&api_key=HAm234DRylBdwr9s80X76mTZTDubUE7Zi1lrUSn0").read
    URI.open(string).read
  end

  def details
    if !params[:id].nil?
      @student = Student.find(params[:id])
    else
      flash[:notice] == 'Not Found.'
      redirect_to root_path
    end
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student details added successfully!' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
    # @student = Student.create!(:first_name => params[:first_name]['first_name'], :last_name => params[:last_name]['last_name'], :age => params[:age]['age'], :email => params[:email]['email'], :phone => params[:phone]['phone'], :address => params[:address]['address'], :city => params[:city]['city'], :state => params[:state]['state'], :country => params[:country]['country'])
    # flash[:notice] = "#{@student.first_name} was added."
    # redirect_to students_index_path
  end

  def new
    @student= Student.new
    @student.build_score
    @student.educations.build
  end

  def edit
    @student = Student.find_by email_id:current_user.email
  end

  def update
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Your profile is successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :phone, :address, :city, :state, :country, score_attributes: [:id, :sat, :act, :gre, :toefl, :ielts], educations_attributes: [:id, :gpa, :college_name, :degree]).merge!({:email_id => current_user.email})
    end
end

app/views/students/_education_fields.html.erb
<fieldset>
  <div class="field">
  <%= f.label :gpa, 'GPA' %>
  <%= f.text_field :gpa  %>
  </div>
  <div class="field">
    <%= f.label :college_name, 'College Name' %>
    <%= f.text_field :college_name  %>
  </div>
  <div class="field">
    <%= f.label :degree, 'Degree' %>
    <%= f.text_field :degree  %>
  </div>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/students/_form.html.erb
<%= form_for @student do |form| %>
  <div class="field">
    <%= form.label :first_name, 'First Name' %>
    <%= form.text_field :first_name %>
  </div>
  <div class="field">
    <%= form.label :last_name, 'Last Name' %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age, 'Age' %>
    <%= form.text_field :age %>
  </div>
  <div class="field">
    <%= form.label :phone, 'Phone Number' %>
    <%= form.text_field :phone %>
  </div>
  <div class="field">
    <%= form.label :address, 'Address' %>
    <%= form.text_field :address %>
  </div>
  <div class="field">
    <%= form.label :city, 'City' %>
    <%= form.text_field :city %>
  </div>
  <div class="field">
    <%= form.label :state, 'State' %>
    <%= form.text_field :state %>
  </div>
  <div class="field">
    <%= form.label :country, 'Country' %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.fields_for :educations do |f| %>
      <%= render 'education_fields', f: f %>
    <% end %>
    <%= link_to_add_fields "Add Education", form, :educations %>
  </div>

  <div class="field">
    <%= form.fields_for :score do |f| %>
      <%= render 'score_fields', f: f %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>

    $('form').on('click', '.remove-fields', function(event) {
        console.log('clicked')
        $(this).prev('input[type=hidden]').val('1');
        $(this).closest('fieldset').hide();
        return event.preventDefault();
    });

    $('form').on('click', '.add_fields', function(event) {
        console.log('clicked!')
        var regexp, time;
        time = new Date().getTime();
        regexp = new RegExp($(this).data('id'), 'g');
        $(this).before($(this).data('fields').replace(regexp, time));
        return event.preventDefault();
    });
</script>

app/views/students/_score_fields.html.erb
<div class="field">
<%= f.label :sat, 'Sat Score' %>
<%= f.text_field :sat  %>
</div>
  <div class="field">
<%= f.label :sat, 'ACT Score' %>
<%= f.text_field :act  %>
  </div>
    <div class="field">
<%= f.label :sat, 'GRE Score' %>
<%= f.text_field :gre  %>
    </div>
      <div class="field">
<%= f.label :sat, 'TOEFL Score' %>
<%= f.text_field :toefl  %>
      </div>
        <div class="field">
<%= f.label :sat, 'IELTS Score' %>
<%= f.text_field :ielts  %>
        </div>

app/views/students/details.html.haml
%h1 Student details

%br

%table#student
  %thead
    %tr
      %th First Name
      %th Last name
      %th Age
      %th Email
      %th Phone
      %th Address
      %th City
      %th State
      %th Country
  %tbody
    %tr
      %td= @student.first_name
      %td= @student.last_name
      %td= @student.age
      %td= @student.email_id
      %td= @student.phone
      %td= @student.address
      %td= @student.city
      %td= @student.state
      %td= @student.country

%br
%br

= link_to 'Leave review', students_index_path
%br

= link_to 'Message', students_index_path
%br

= link_to 'Back', students_index_path

app/views/students/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', student: @student %>

app/views/students/index.html.haml
%h1{:style => 'text-align:center'} Faculty Home

%table#students{:width=>"100%",:class  => "table table-dark"}
  %thead
    %tr
      %th= link_to 'First Name', students_index_path(:order => :first_name)
      %th Last name
      %th= link_to 'Age', students_index_path(:order => :age)
      %th Email
      %th Phone
      %th Address
      %th City
      %th State
      %th Country
      %th= link_to 'GPA', students_index_path(:order => :gpa)
      %th College
      %th Degree
      %th= link_to 'SAT', students_index_path(:order => :sat)
      %th= link_to 'ACT', students_index_path(:order => :act)
      %th GRE
      %th TOEFL
      %th IELTS
      %th More
  %tbody
    - @students.each do |student|
      %tr
        %td= student.first_name
        %td= student.last_name
        %td= student.age
        %td= student.email_id
        %td= student.phone
        %td= student.address
        %td= student.city
        %td= student.state
        %td= student.country
        %td= if (Education.find_by_student_id(student.id).respond_to?(:gpa)) then Education.find_by_student_id(student.id).gpa; end
        %td= if (Education.find_by_student_id(student.id).respond_to?(:college_name)) then Education.find_by_student_id(student.id).college_name; end
        %td= if (Education.find_by_student_id(student.id).respond_to?(:degree)) then Education.find_by_student_id(student.id).degree; end
        %td= if (Score.find_by_student_id(student.id).respond_to?(:sat)) then Score.find_by_student_id(student.id).sat; end
        %td= if (Score.find_by_student_id(student.id).respond_to?(:act)) then Score.find_by_student_id(student.id).act; end
        %td= if (Score.find_by_student_id(student.id).respond_to?(:gre)) then Score.find_by_student_id(student.id).gre; end
        %td= if (Score.find_by_student_id(student.id).respond_to?(:toefl)) then Score.find_by_student_id(student.id).toefl; end
        %td= if (Score.find_by_student_id(student.id).respond_to?(:ielts)) then Score.find_by_student_id(student.id).ielts; end
        %td= link_to 'details', students_details_path(:id => student.id)

app/views/students/new.html.erb
<h1>Add Student details</h1>

<%= render 'form', student: @student %>

app/views/students/show.html.haml
%h1 Home

%br

%h2 Search colleges
%table#colleges{:width=>"100%",:class=>"table table-striped"}
  %thead
    %tr
      %th Institution Name
      %th Class Size
      %th Acceptance Rate
      %th Tuition
      %th Standardized Tests
      %th Location
      %th More info
  %tbody
    - @universities.each do |univ|
      %tr
        %td= univ['school.name']
        %td= univ['2013.student.size']
        %td= if univ['2015.admissions.admission_rate.overall'] != nil then univ['2015.admissions.admission_rate.overall'] else 1.0; end
        %td= univ['2015.cost.avg_net_price.public']
        %td= if (univ['2015.admissions.test_requirements'] == 1) then 'Required' elsif (univ['2015.admissions.test_requirements'] == 2) then 'Recommended' elsif (univ['2015.admissions.test_requirements'] == '') then '' else 'Not Required'; end
        %th= if(univ['school.city'] != nil) then univ['school.city'] + ',' + univ['school.state']; end
        %th= if univ['school.school_url'] then (if (univ['school.school_url'][0] != 'h') then (link_to univ['school.school_url'], 'https://' + univ['school.school_url']) else (link_to univ['school.school_url'], univ['school.school_url']); end ); end
        %th= if univ['school.state'] then link_to 'View Programs', programs_path(:school => univ['id']); end

%br
  = form_tag students_show_path do

    = label :search_terms, 'Search to view university info:'
    = text_field_tag :search_box

    = submit_tag 'Search Universities', :id => 'search_button'
%br

%h2 Ranking statistics
%table#rankings{:width=>"50%",:class=>"table table-striped"}
  %thead
    %tr
      %th GPA Percentile
      %th Standardized Tests Percentile
      %th Estimated (%) Chance of Acceptance
  %tbody
    %tr
      %td{:style => 'text-align:center'}= @gpa_rank / @total * 100
      %td{:style => 'text-align:center'}= @act_rank / @total * 100
      %td{:style => 'text-align:center'}= (1 - (@gpa_rank /@total + @act_rank/@total)/2) * 100

%br
%br

%h2 Profile Info
%table#students{:width=>"65%",:class=>"table table-striped"}
  %thead
    %tr
      %th First Name
      %th Last name
      %th Age
      %th Email
      %th Phone
      %th Address
      %th City
      %th State
      %th Country
  %tbody
    %tr
      %td{:style => 'text-align:center'}= @student.first_name
      %td{:style => 'text-align:center'}= @student.last_name
      %td{:style => 'text-align:center'}= @student.age
      %td{:style => 'text-align:center'}= @student.email_id
      %td{:style => 'text-align:center'}= @student.phone
      %td{:style => 'text-align:center'}= @student.address
      %td{:style => 'text-align:center'}= @student.city
      %td{:style => 'text-align:center'}= @student.state
      %td{:style => 'text-align:center'}= @student.country
= link_to "Edit personal information", edit_student_path(current_user.id)
%br
%br
%h2 My applications
= link_to "View my applications", student_applications_path(@student)