config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :conversations
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'pages#landing'
  post '/', to: 'pages#landing'

  post 'update_university', to: 'pages#update_university'

  get 'students/show', to: 'students#show'
  post 'students/show', to: 'students#show'

  get 'students/details', to: 'students#details'

  get 'ratings/index', to: 'ratings#index'

  post 'ratings/create', to: 'ratings#create'
  get 'ratings/new', to: 'ratings#new'

  resources :conversations do
    resources :messages
  end

  get 'students/index', to: 'students#index'
  resources :students

  get 'scores/index', to: 'scores#index'
  resources :scores

  get 'educations/index', to: 'educations#index'
  resources :educations

  get 'student_applications/index'
  resources :student_applications
  post 'student_applications/save_application'

  get 'programs/index'
  resources :programs

  get 'admin', to: 'pages#admin'
  post 'pages/update_users', to: 'pages#update_users'

  patch 'students/:id', to: 'students#update'                          # update (as needed)
  put 'students/:id', to: 'students#update'

  get 'faculty/index', to: 'student_applications#faculty_index'

  post 'ratings/create_from_application', to: 'ratings#create_from_application'
  post 'application/update_status', to: 'student_applications#update_status'

  get 'ratings/application', to: 'ratings#show_application_ratings'
  get 'ratings/user', to: 'ratings#show_user_ratings'

end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    # @score = Score.new(score_params)
    #
    # respond_to do |format|
    #   if @score.save
    #     format.html { redirect_to @score, notice: 'Score was successfully created.' }
    #     format.json { render :show, status: :created, location: @score }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @score.errors, status: :unprocessable_entity }
    #   end
    # end
    # end
    @score = Score.create!(:sat => params[:sat]['sat'], :act => params[:act]['act'], :gre => params[:gre]['gre'], :toefl => params[:toefl]['toefl'], :ielts => params[:ielts]['ielts'])
    flash[:notice] = "Scores were added."
    redirect_to scores_index_path
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:sat, :act, :gre, :toefl, :ielts)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sat %><br>
    <%= f.number_field :sat %>
  </div>
  <div class="field">
    <%= f.label :act %><br>
    <%= f.number_field :act %>
  </div>
  <div class="field">
    <%= f.label :gre %><br>
    <%= f.number_field :gre %>
  </div>
  <div class="field">
    <%= f.label :toefl %><br>
    <%= f.number_field :toefl %>
  </div>
  <div class="field">
    <%= f.label :ielts %><br>
    <%= f.text_field :ielts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scores</h1>

<table>
  <thead>
    <tr>
      <th>Sat</th>
      <th>Act</th>
      <th>Gre</th>
      <th>Toefl</th>
      <th>Ielts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.sat %></td>
        <td><%= score.act %></td>
        <td><%= score.gre %></td>
        <td><%= score.toefl %></td>
        <td><%= score.ielts %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/index.html.haml
%h1 Exam scores

%table#scores
  %thead
    %tr
      %th ID
      %th SAT
      %th ACT
      %th GRE
      %th TOEFL
      %th IELTS

  %tbody
    - @scores.each do |score|
      %tr
        %td= score.id
        %td= score.sat
        %td= score.act
        %td= score.gre
        %td= score.toefl
        %td= score.ielts

= link_to 'add new', new_student_path

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sat:</strong>
  <%= @score.sat %>
</p>

<p>
  <strong>Act:</strong>
  <%= @score.act %>
</p>

<p>
  <strong>Gre:</strong>
  <%= @score.gre %>
</p>

<p>
  <strong>Toefl:</strong>
  <%= @score.toefl %>
</p>

<p>
  <strong>Ielts:</strong>
  <%= @score.ielts %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>