config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :conversations
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'pages#landing'
  post '/', to: 'pages#landing'

  post 'update_university', to: 'pages#update_university'

  get 'students/show', to: 'students#show'
  post 'students/show', to: 'students#show'

  get 'students/details', to: 'students#details'

  get 'ratings/index', to: 'ratings#index'

  post 'ratings/create', to: 'ratings#create'
  get 'ratings/new', to: 'ratings#new'

  resources :conversations do
    resources :messages
  end

  get 'students/index', to: 'students#index'
  resources :students

  get 'scores/index', to: 'scores#index'
  resources :scores

  get 'educations/index', to: 'educations#index'
  resources :educations

  get 'student_applications/index'
  resources :student_applications
  post 'student_applications/save_application'

  get 'programs/index'
  resources :programs

  get 'admin', to: 'pages#admin'
  post 'pages/update_users', to: 'pages#update_users'

  patch 'students/:id', to: 'students#update'                          # update (as needed)
  put 'students/:id', to: 'students#update'

  get 'faculty/index', to: 'student_applications#faculty_index'

  post 'ratings/create_from_application', to: 'ratings#create_from_application'
  post 'application/update_status', to: 'student_applications#update_status'

  get 'ratings/application', to: 'ratings#show_application_ratings'
  get 'ratings/user', to: 'ratings#show_user_ratings'

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :student
  has_many :student_applications
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    # @education = Education.new(education_params)
    #
    # respond_to do |format|
    #   if @education.save
    #     format.html { redirect_to @education, notice: 'Education was successfully created.' }
    #     format.json { render :show, status: :created, location: @education }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @education.errors, status: :unprocessable_entity }
    #   end
    # end

    @education = Education.create!(:gpa => params[:gpa]['gpa'], :college_name => params[:college_name]['college_name'], :degree => params[:degree]['degree'])
    flash[:notice] = "Educational Qualifications were added."
    redirect_to educations_index_path
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:gpa, :college_name, :degree)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gpa %><br>
    <%= f.text_field :gpa %>
  </div>
  <div class="field">
    <%= f.label :college_name %><br>
    <%= f.text_field :college_name %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Educations</h1>

<table>
  <thead>
    <tr>
      <th>Gpa</th>
      <th>College name</th>
      <th>Degree</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.gpa %></td>
        <td><%= education.college_name %></td>
        <td><%= education.degree %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

app/views/educations/index.html.haml
%h1 Education Information

%table#scores
  %thead
    %tr
      %th College Name
      %th Degree
      %th GPA

  %tbody
    - @educations.each do |education|
      %tr
        %td= education.college_name
        %td= education.degree
        %td= education.gpa


= link_to 'add new', new_student_path

app/views/educations/new.html.erb
<h1>New Education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gpa:</strong>
  <%= @education.gpa %>
</p>

<p>
  <strong>College name:</strong>
  <%= @education.college_name %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @education.degree %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>