config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :conversations
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'pages#landing'
  post '/', to: 'pages#landing'

  post 'update_university', to: 'pages#update_university'

  get 'students/show', to: 'students#show'
  post 'students/show', to: 'students#show'

  get 'students/details', to: 'students#details'

  get 'ratings/index', to: 'ratings#index'

  post 'ratings/create', to: 'ratings#create'
  get 'ratings/new', to: 'ratings#new'

  resources :conversations do
    resources :messages
  end

  get 'students/index', to: 'students#index'
  resources :students

  get 'scores/index', to: 'scores#index'
  resources :scores

  get 'educations/index', to: 'educations#index'
  resources :educations

  get 'student_applications/index'
  resources :student_applications
  post 'student_applications/save_application'

  get 'programs/index'
  resources :programs

  get 'admin', to: 'pages#admin'
  post 'pages/update_users', to: 'pages#update_users'

  patch 'students/:id', to: 'students#update'                          # update (as needed)
  put 'students/:id', to: 'students#update'

  get 'faculty/index', to: 'student_applications#faculty_index'

  post 'ratings/create_from_application', to: 'ratings#create_from_application'
  post 'application/update_status', to: 'student_applications#update_status'

  get 'ratings/application', to: 'ratings#show_application_ratings'
  get 'ratings/user', to: 'ratings#show_user_ratings'

end

app/models/student_application.rb
class StudentApplication < ActiveRecord::Base
  belongs_to :student
  belongs_to :score
  belongs_to :education
end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  before_action :confirm_student, only: :edit
  before_action :confirm_faculty, only: :faculty_index
  before_action :check_faculty

  def check_faculty
    if current_user.faculty? and current_user.status == 'Unconfirmed'
      flash[:notice] = 'You need to be approved by the Admin before viewing and approving applications! Contact admin@gmail.com to get your account approved.'
      redirect_to(root_path)
    end
  end



  def confirm_student
    if !current_user.student?
      redirect_to root_path
    end
  end

  def confirm_faculty
    if !current_user.faculty?
      redirect_to root_path
    end
  end
  def show
    application_id = params[:id]
    @student_application = StudentApplication.find(application_id)
    @student = Student.find(StudentApplication.find(application_id).student_id)

    @ratings = Rating.where("student_application_id = '#{application_id}'")
    @avg_ratings = 0
    @num_ratings = 0
    @ratings.each do |rating|
      @avg_ratings = @avg_ratings + rating.rating
      @num_ratings = @num_ratings + 1
    end
    if(@num_ratings == 0)
      @avg_ratings = "No ratings yet"
      @num_ratings = "No ratings yet"
    else
      @avg_ratings = @avg_ratings / @num_ratings
    end
  end

  def index
    @student_applications = StudentApplication.where("student_id = #{(Student.find_by_email_id(current_user.email).id)}")
    # Student.where("id = #{student_application.student_id}").first
  end

  def faculty_index
    if !StudentApplication.where("university_name = '#{Faculty.where("email_id = '#{current_user.email}'").first.university_name}'").nil?
      @student_applications = StudentApplication.where("university_name = '#{Faculty.where("email_id = '#{current_user.email}'").first.university_name}'")
    else
      @student_applications = {}
    end
    
    order = params[:order]

    if order == 'age'
      ordering = 'age ASC'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'first_name'
      ordering = 'first_name desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'gpa'
      ordering = 'gpa desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'sat'
      ordering = 'sat desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'act'
      ordering = 'act desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'gre'
      ordering = 'gre desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'toefl'
      ordering = 'toefl desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    elsif order == 'ielts'
      ordering = 'ielts desc'
      @student_applications = StudentApplication.all.reorder(ordering)
    end
  end

  def new
    @university_program = params[:program]
  end

  def edit
    application_id = params[:id]
    @student_application = StudentApplication.find(application_id)
  end

  def update
    application_id = params[:id]
    @student_application = StudentApplication.find(application_id)
    student_application_update = ActionController::Parameters.new(params[:student_application]).permit(:application_id, :university_name, :program, :degree, :year_start, :first_name, :last_name, :attended_university_name, :university_degree, :gpa, :sat, :act, :gre, :toefl, :ielts)
    @student_application.update_attributes!(student_application_update)
    redirect_to edit_student_application_path(@student_application)
  end

  def destroy
    application_id = params[:id]
    @student_application = StudentApplication.find(application_id)
    @student_application.destroy
    redirect_to student_applications_path
  end

  def save_application
    @student_application = StudentApplication.new(params.require(:student_application).permit(:application_id, :university_name, :program, :degree, :year_start, :first_name, :last_name, :attended_university_name, :university_degree, :gpa, :sat, :act, :gre, :toefl, :ielts))

    @student_application.university_name = params[:program][:university_name]
    @student_application.program = params[:program][:program]
    @student_application.degree = params[:program][:degree]
    @student_application.year_start = params[:program][:year_start]

    @student_application.student = Student.find_by_email_id(current_user.email)
    @student_application.score = Score.create(:act => @student_application.act, :gre => @student_application.gre, :toefl => @student_application.toefl, :ielts => @student_application.ielts)
    @student_application.education = Education.create(:gpa => @student_application.gpa, :college_name => @student_application.attended_university_name, :degree => @student_application.university_degree)

    @student_application.application_id = StudentApplication.count + 1
    @student_application.save

    redirect_to student_applications_path
  end

  def update_status
    StudentApplication.find(params[:application_id]).update_column('status', params[:Application][:status])
    redirect_to student_application_path(StudentApplication.find(params[:application_id]))
  end
end

app/views/student_applications/edit.html.haml
%h1 Application Details

= form_tag student_application_path(@student_application), :method => :put, :id => 'save_application' do

  Institution:
  = label :student_application, :university_name, @student_application['university_name']
  %br
  Program:
  = label :student_application, :program_name, @student_application['program']
  %br
  Degree:
  = label :student_application, :degree, @student_application['degree']
  %br
  Year of Application:
  = label :student_application, :year_start, @student_application['year_start']
  %br
  = label :student_application, :first_name, 'First Name'
  = text_field :student_application, 'first_name'
  %br
  = label :student_application, :last_name, 'Last Name'
  = text_field :student_application, 'last_name'
  %br
  Education History
  %br
  = label :student_application, :attended_university_name, 'University'
  = text_field :student_application, 'attended_university_name'
  %br
  = label :student_application, :university_degree, 'Degree'
  = select :student_application, :university_degree, ['','BS', 'BA', 'MS', 'MA', 'PhD']
  %br
  = label :student_application, :gpa, 'GPA'
  = text_field :student_application, 'gpa'
  %br
  = label :student_application, :sat, 'SAT'
  = text_field :student_application, 'sat'
  %br
  = label :student_application, :act, 'ACT'
  = text_field :student_application, 'act'
  %br
  = label :student_application, :gre, 'GRE'
  = text_field :student_application, 'gre'
  %br
  = label :student_application, :toefl, 'TOEFL'
  = text_field :student_application, 'toefl'
  %br
  = label :student_application, :ielts, 'IELTS'
  = text_field :student_application, 'ielts'
  %br
  = submit_tag 'Save Changes'
= link_to 'View Applications', student_applications_path
= link_to 'Delete Application', student_application_path(@student_application), :method => :delete, :confirm => 'Are you sure you want to delete this application?'
%br
= link_to 'Return to Previous Page', student_applications_path

app/views/student_applications/faculty_index.html.haml
%h1{:style => 'text-align:center'} Applications

%table#student_applications{:width=>"100%", :class=>"table"}
  %thead{:class=>"thead-dark"}
    %tr
      %th= link_to 'First Name', faculty_index_path(:order => :first_name)
      %th Last Name
      %th Email
      %th Institution
      %th Program
      %th Degree
      %th Begin Year
      %th= link_to 'GPA', faculty_index_path(:order => :gpa)
      %th= link_to 'SAT', faculty_index_path(:order => :sat)
      %th= link_to 'ACT', faculty_index_path(:order => :act)
      %th= link_to 'GRE', faculty_index_path(:order => :gre)
      %th= link_to 'TOEFL', faculty_index_path(:order => :toefl)
      %th= link_to 'IELTS', faculty_index_path(:order => :ielts)
      %th Avg Rating
      %th Num Ratings
      %th Status
      %th Details
  %tbody
    - @student_applications.each do |student_application|
      %tr
        %td= student_application.first_name
        %td= student_application.last_name
        %td= Student.where("id = #{student_application.student_id}").first.email_id
        %td= student_application.university_name
        %td= student_application.program
        %td= student_application.degree
        %td= student_application.year_start
        %td= student_application.gpa
        %td= student_application.sat
        %td= student_application.act
        %td= student_application.gre
        %td= student_application.toefl
        %td= student_application.ielts
        %td= Rating.average(student_application.id)
        %td= Rating.number(student_application.id)
        %td= student_application.status
        %td= link_to "View", student_application_path(student_application)

%br
= link_to 'View My Ratings', ratings_user_path(:user_id => current_user.id)
%br
= link_to 'Return to Previous Page', students_show_path

app/views/student_applications/index.html.haml
%h1 Applications

%table#student_applications{:cellpadding => 1, :cellspacing => 10}
  %thead
    %tr
      %th Institution
      %th Program
      %th Degree
      %th Begin Year
  %tbody
    - @student_applications.each do |student_application|
      %tr
        %td= student_application.university_name
        %td= student_application.program
        %td= student_application.degree
        %td= student_application.year_start
        %td= link_to "View", student_application_path(student_application)
        %td= link_to "Edit", edit_student_application_path(student_application)
        %td= link_to "Delete", student_application_path(student_application), :method => :delete, :confirm => 'Are you sure you want to delete this application?'

= link_to 'Return to Home Page', students_show_path

app/views/student_applications/new.html.haml
%h1 Application Details

= form_tag student_applications_save_application_path(:program => @university_program), :method => :post, :id => 'save_application' do

  Institution:
  = label :program, :university_name, @university_program['university_name']
  %br
  Program:
  = label :program, :program_name, @university_program['program']
  %br
  Degree:
  = label :program, :degree, @university_program['degree']
  %br
  Year of Application:
  = label :program, :year_start, '2022'
  %br
  = label :student_application, :first_name, 'First Name'
  = text_field :student_application, 'first_name'
  %br
  = label :student_application, :last_name, 'Last Name'
  = text_field :student_application, 'last_name'
  %br
  Education History
  %br
  = label :student_application, :attended_university_name, 'University'
  = text_field :student_application, 'attended_university_name'
  %br
  = label :student_application, :university_degree, 'Degree'
  = select :student_application, :university_degree, ['','BS', 'BA', 'MS', 'MA', 'PhD']
  %br
  = label :student_application, :gpa, 'GPA'
  = text_field :student_application, 'gpa'
  %br
  = label :student_application, :sat, 'SAT'
  = text_field :student_application, 'sat'
  %br
  = label :student_application, :act, 'ACT'
  = text_field :student_application, 'act'
  %br
  = label :student_application, :gre, 'GRE'
  = text_field :student_application, 'gre'
  %br
  = label :student_application, :toefl, 'TOEFL'
  = text_field :student_application, 'toefl'
  %br
  = label :student_application, :ielts, 'IELTS'
  = text_field :student_application, 'ielts'
  %br
  = submit_tag 'Save Changes'
= link_to 'View Applications', student_applications_path
%br
= link_to 'Return to Home Page', students_show_path

app/views/student_applications/show.html.haml
%h1 Application Details

%ul#details
  %li
    Institution:
    = @student_application.university_name
  %li
    Program:
    = @student_application.program
  %li
    Degree:
    = @student_application.degree
  %li
    Year Start:
    = @student_application.year_start
  %li
    First Name:
    = @student_application.first_name
  %li
    Last Name:
    = @student_application.last_name
  %li
    College:
    = @student_application.attended_university_name
  %li
    College Degree:
    = @student_application.university_degree
  %li
    GPA:
    = @student_application.gpa
  %li
    SAT:
    = @student_application.sat
  %li
    ACT:
    = @student_application.act
  %li
    GRE:
    = @student_application.gre
  %li
    TOEFL:
    = @student_application.toefl
  %li
    IELTS:
    = @student_application.ielts
  %li
    Average Rating:
    = @avg_ratings
  %li
    Number of Ratings:
    = @num_ratings
  %li
    Status:
    = @student_application.status


- if (current_user.faculty?)
  = link_to 'View Ratings', ratings_application_path(:app_id => @student_application.id)
  %br
  %br
  %h5 Review Application
  = form_tag ratings_create_from_application_path(:application_id => @student_application.id) do
    = label :rating, :rating, 'Rating'
    = select :rating, :rating, [1,2,3,4,5]
    = label :rating, :comment, 'comment'
    = text_field :comment, 'comment'
    = submit_tag 'Leave Rating'
  = link_to 'View Ratings', ratings_application_path(:app_id => @student_application.id)
  %br
  %br
  %h5 Update Application Status
  = form_tag application_update_status_path(:application_id => @student_application.id) do
    = label :Application, :application, 'Application Status'
    = select :Application, :status, %w[Accepted Declined Waitlisted]
    = submit_tag 'Leave Rating'

  %br
- if (current_user.student?)
  = link_to 'Edit Application', edit_student_application_path(@student_application)
  = link_to 'Delete Application', student_application_path(@student_application), :method => :delete, :confirm => 'Are you sure you want to delete this application?'
%br
-#= link_to 'Return to Previous Page', student_applications_path